name: "CI: Build & Release"

on: [ push, pull_request ]

jobs:
  windows-vs:
    name: Build on Windows (Visual Studio 2022)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install SDL2 via vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git vcpkg
          .\vcpkg\bootstrap-vcpkg.bat
          .\vcpkg\vcpkg install sdl2:x64-windows
          $env:VCPKG_ROOT="$PWD\vcpkg"

      - name: Build with MSBuild
        shell: pwsh
        run: |
          "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe" /p:Configuration=Release /p:Platform=x64

  windows-cmake:
    name: Build on Windows (CMake)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install vcpkg and SDL2
        run: |
          git clone https://github.com/microsoft/vcpkg.git vcpkg
          .\vcpkg\bootstrap-vcpkg.bat
          .\vcpkg\vcpkg install sdl2:x64-windows
          echo "VCPKG_ROOT=$PWD\vcpkg" >> $env:GITHUB_ENV

      - name: Build with CMake
        run: |
          cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=${{ env.VCPKG_ROOT }}\scripts\buildsystems\vcpkg.cmake
          cmake --build build --config Release
        shell: pwsh

  linux-make:
    name: Build on Linux (make)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install SDL2 dev packages
        run: |
          sudo apt-get update
          sudo apt-get install -y libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev build-essential

      - name: Build with make
        run: |
          make

  linux-cmake:
    name: Build on Linux (cmake)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install SDL2 dev packages
        run: |
          sudo apt-get update
          sudo apt-get install -y libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev build-essential

      - name: Build with CMake
        run: |
          cmake -B build -S .
          cmake --build build --config Release
        shell: pwsh

