name: "CI: Build & Release"

on: [ push, pull_request ]

jobs:
  build-windows:
    name: Build on Windows (Visual Studio 2022)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install SDL2 via vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git vcpkg
          .\vcpkg\bootstrap-vcpkg.bat
          .\vcpkg\vcpkg install sdl2:x64-windows

      - name: Build with MSBuild
        shell: pwsh
        run: |
          $env:VCPKG_ROOT="$PWD\vcpkg"
          $env:VCPKG_TARGET_TRIPLET = "x64-windows"
          msbuild.exe /p:Configuration=Release /p:Platform=x64 /p:VcpkgRoot="%VCPKG_ROOT%" /p:VcpkgTriplet="%VCPKG_TARGET_TRIPLET%" .

  build-linux:
    name: Build on Linux (make)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install SDL2 dev packages
        run: |
          sudo apt-get update
          sudo apt-get install -y libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev build-essential

      - name: Build with make
        run: |
          make
